openapi: 3.1.0
info:
  title: example
paths: {}
components:
  schemas:
    example.CombinedDefinition:
      type: object
      oneOf:
        - type: object
          properties:
            a:
              title: a
              $ref: '#/components/schemas/a'
          title: a
          required:
            - a
        - type: object
          properties:
            b:
              title: b
              $ref: '#/components/schemas/b'
          title: b
          required:
            - b
      properties:
        commonId:
          type: integer
          title: common_id
          format: int32
      title: CombinedDefinition
      additionalProperties: false
    example.DefinitionA:
      type: object
      properties:
        id:
          type: integer
          title: id
          format: int32
        name:
          type: string
          title: name
      title: DefinitionA
      additionalProperties: false
    example.DefinitionB:
      type: object
      properties:
        description:
          type: string
          title: description
        active:
          type: boolean
          title: active
      title: DefinitionB
      additionalProperties: false
security: []
