#!/usr/bin/env bash

# Builds a demo directory for one input: documentation sites and generated
# type code, written to out/<name>/. The input is normally a .proto file, in
# which case the plugin is built from this repository and used to generate
# both the OpenAPI spec and the JSON Schema bundle first. An already-generated
# spec file is also accepted. Tools that fail are reported and skipped so one
# incompatible tool doesn't hide the others.
set -eo pipefail

ORIGINAL_CWD="$(pwd)"
DIR="$(CDPATH= cd "$(dirname "${0}")/.." && pwd)"
REPO_DIR="$(CDPATH= cd "${DIR}/.." && pwd)"
cd "${DIR}"

usage() {
    echo "usage: ${0} <path-to-proto-or-spec>" >&2
    echo "  <path-to-proto-or-spec> is a .proto file (specs are generated first)," >&2
    echo "  or an OpenAPI / JSON Schema file already generated by protoc-gen-connect-openapi." >&2
    exit 1
}

[ -n "${1-}" ] || usage

INPUT_PATH="${1}"
if [[ "${INPUT_PATH}" != /* ]]; then
    INPUT_PATH="${ORIGINAL_CWD}/${INPUT_PATH}"
fi
[ -f "${INPUT_PATH}" ] || { echo "input not found: ${INPUT_PATH}" >&2; exit 1; }

INPUT_FILE="$(basename "${INPUT_PATH}")"
FAILED_STEPS=()
ARTIFACT_LINKS=""

detect_kind() {
    local input="${1}"
    case "${input}" in
    *.proto)
        echo "proto"
        return
        ;;
    *.jsonschema.json)
        echo "jsonschema"
        return
        ;;
    esac
    if grep -qE '^ *("openapi"|openapi) *:' "${input}"; then
        echo "openapi"
        return
    fi
    if grep -q '"\$defs"' "${input}"; then
        echo "jsonschema"
        return
    fi
    echo "unknown"
}

run_step() {
    local name="${1}"
    shift
    echo "==> ${name}"
    if "${@}"; then
        return 0
    fi
    echo "WARN: '${name}' failed; continuing with the remaining tools" >&2
    FAILED_STEPS+=("${name}")
    return 0
}

# render_template <template> <target-dir> <spec-file>: instantiates an HTML
# shell that loads the spec sitting next to it.
render_template() {
    local template="${1}"
    local target_dir="${2}"
    local spec_file="${3}"
    sed -e "s|__SPEC_FILE__|${spec_file}|g" -e "s|__SPEC_NAME__|${BASE_NAME}|g" \
        "templates/${template}" >"${target_dir}/${template}"
}

# add_artifact <path-relative-to-OUT_DIR> <label>: records a link for the
# demo's index page if the file was actually produced.
add_artifact() {
    local file="${1}"
    local label="${2}"
    if [ -s "${OUT_DIR}/${file}" ]; then
        ARTIFACT_LINKS="${ARTIFACT_LINKS}<li><a href=\"./${file}\">${label}</a></li>"
    fi
}

build_plugin() {
    local plugin_bin="${1}"
    (cd "${REPO_DIR}" && go build -o "${plugin_bin}" .)
}

# generate_specs <proto>: builds the plugin from this repository and generates
# both spec kinds for the proto file. The proto's buf module root is found by
# walking up to the nearest buf.yaml so imports resolve; a plain directory of
# self-contained protos works too.
generate_specs() {
    local proto="${1}"
    local plugin_bin="${DIR}/out/.bin/protoc-gen-connect-openapi"

    mkdir -p "${DIR}/out/.bin"
    run_step "build protoc-gen-connect-openapi from this repository" \
        build_plugin "${plugin_bin}"
    [ -x "${plugin_bin}" ] || { echo "plugin build failed; cannot generate specs" >&2; exit 1; }

    local module_root
    module_root="$(dirname "${proto}")"
    local search="${module_root}"
    while [ "${search}" != "/" ]; do
        if [ -f "${search}/buf.yaml" ]; then
            module_root="${search}"
            break
        fi
        search="$(dirname "${search}")"
    done

    local template
    template="$(cat <<EOF
{"version":"v2","plugins":[
  {"local":["${plugin_bin}"],"out":"${DIR}/${OUT_DIR}/openapi","opt":["format=yaml","path=${BASE_NAME}.openapi.yaml"]},
  {"local":["${plugin_bin}"],"out":"${DIR}/${OUT_DIR}/jsonschema","opt":["format=jsonschema","path=${BASE_NAME}.jsonschema.json"]}
]}
EOF
)"
    echo "==> generating specs with buf (module root: ${module_root})"
    buf generate --template "${template}" "${module_root}" --path "${proto}"
}

build_openapi() {
    local spec_file="${1}"
    local target_dir="${OUT_DIR}/openapi"

    run_step "redoc static docs" \
        npx @redocly/cli build-docs "${target_dir}/${spec_file}" -o "${target_dir}/redoc.html"
    add_artifact "openapi/redoc.html" "Redoc (static build)"

    render_template "scalar.html" "${target_dir}" "${spec_file}"
    add_artifact "openapi/scalar.html" "Scalar (CDN)"

    render_template "swagger-ui.html" "${target_dir}" "${spec_file}"
    add_artifact "openapi/swagger-ui.html" "Swagger UI (CDN)"

    render_template "elements.html" "${target_dir}" "${spec_file}"
    add_artifact "openapi/elements.html" "Stoplight Elements (CDN)"

    run_step "openapi-typescript types" \
        npx openapi-typescript "${target_dir}/${spec_file}" -o "${target_dir}/types.ts"
    add_artifact "openapi/types.ts" "TypeScript types (openapi-typescript)"

    add_artifact "openapi/${spec_file}" "OpenAPI source (${spec_file})"
}

build_jsonschema() {
    local spec_file="${1}"
    local target_dir="${OUT_DIR}/jsonschema"

    # Type generators need a root schema; the generated bundle only has $defs.
    run_step "wrap \$defs bundle for codegen" \
        node scripts/wrap_defs.mjs "${target_dir}/${spec_file}" "${target_dir}/wrapped.schema.json"

    run_step "json-schema-for-humans docs" \
        uvx --from json-schema-for-humans generate-schema-doc \
        --config expand_buttons=true --config link_to_reused_ref=false \
        "${target_dir}/wrapped.schema.json" "${target_dir}/schema-docs.html"
    add_artifact "jsonschema/schema-docs.html" "json-schema-for-humans (static docs)"

    if [ -s "${target_dir}/wrapped.schema.json" ]; then
        run_step "json-schema-to-typescript types" \
            npx json2ts --input "${target_dir}/wrapped.schema.json" --output "${target_dir}/types.ts" --cwd "${target_dir}"
        add_artifact "jsonschema/types.ts" "TypeScript types (json-schema-to-typescript)"

        run_step "quicktype Go types" \
            npx quicktype --src-lang schema --lang go --package demo \
            -o "${target_dir}/types.go" "${target_dir}/wrapped.schema.json"
        add_artifact "jsonschema/types.go" "Go types (quicktype)"
    fi

    add_artifact "jsonschema/${spec_file}" "JSON Schema source (${spec_file})"
    add_artifact "jsonschema/wrapped.schema.json" "Codegen wrapper schema"
}

write_index() {
    local kind="${1}"
    cat >"${OUT_DIR}/index.html" <<EOF
<!doctype html>
<html>
  <head>
    <title>${BASE_NAME}</title>
    <meta charset="utf-8" />
    <style>body { font-family: system-ui, sans-serif; max-width: 40rem; margin: 3rem auto; }</style>
  </head>
  <body>
    <h1>${BASE_NAME}</h1>
    <p>Input: ${INPUT_FILE} (${kind})</p>
    <ul>${ARTIFACT_LINKS}</ul>
    <p><a href="../">back to all demos</a></p>
  </body>
</html>
EOF
}

# write_root_index regenerates out/index.html linking every built demo.
write_root_index() {
    local links=""
    local dir
    for dir in out/*/; do
        [ -d "${dir}" ] || continue
        local name
        name="$(basename "${dir}")"
        [ "${name}" = ".bin" ] && continue
        links="${links}<li><a href=\"./${name}/\">${name}</a></li>"
    done
    cat >"out/index.html" <<EOF
<!doctype html>
<html>
  <head>
    <title>protoc-gen-connect-openapi demos</title>
    <meta charset="utf-8" />
    <style>body { font-family: system-ui, sans-serif; max-width: 40rem; margin: 3rem auto; }</style>
  </head>
  <body>
    <h1>protoc-gen-connect-openapi demos</h1>
    <ul>${links}</ul>
  </body>
</html>
EOF
}

KIND="$(detect_kind "${INPUT_PATH}")"
if [ "${KIND}" = "unknown" ]; then
    echo "could not detect input kind for ${INPUT_PATH}: expected .proto, OpenAPI, or a JSON Schema \$defs bundle" >&2
    exit 1
fi

BASE_NAME="${INPUT_FILE%.*}"
BASE_NAME="${BASE_NAME%.openapi}"
BASE_NAME="${BASE_NAME%.jsonschema}"
OUT_DIR="out/${BASE_NAME}"

rm -rf "${OUT_DIR}"
mkdir -p "${OUT_DIR}"
echo "==> building ${KIND} demo for ${INPUT_FILE} in demo/${OUT_DIR}"

case "${KIND}" in
proto)
    generate_specs "${INPUT_PATH}"
    build_openapi "${BASE_NAME}.openapi.yaml"
    build_jsonschema "${BASE_NAME}.jsonschema.json"
    ;;
openapi)
    mkdir -p "${OUT_DIR}/openapi"
    cp "${INPUT_PATH}" "${OUT_DIR}/openapi/${INPUT_FILE}"
    build_openapi "${INPUT_FILE}"
    ;;
jsonschema)
    mkdir -p "${OUT_DIR}/jsonschema"
    cp "${INPUT_PATH}" "${OUT_DIR}/jsonschema/${INPUT_FILE}"
    build_jsonschema "${INPUT_FILE}"
    ;;
esac

write_index "${KIND}"
write_root_index

echo ""
echo "==> built demo/${OUT_DIR}"
if [ "${#FAILED_STEPS[@]}" -gt 0 ]; then
    echo "==> tools that failed on this input (this can be informative in itself):"
    printf '    - %s\n' "${FAILED_STEPS[@]}"
fi
